In [46]:
#####DATA PREPROCESSING

In [1]:
import numpy as np
import os
import cv2  # Corrected import statement for OpenCV
import random
import matplotlib.pyplot as plt
import pickle


In [2]:
%matplotlib inline

In [3]:
DIRECTORY = r'C:\Users\trish\Downloads\archive\dogscats\dogscats\valid'
CATEGORIES= ['cats','dogs']

In [4]:
data = []

for category in CATEGORIES:
    path = os.path.join(DIRECTORY, category)
    for img in os.listdir(path):
        img_path = os.path.join(path, img)
        label = CATEGORIES.index(category)
        arr = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        new_arr = cv2.resize(arr, (60, 60))
        data.append([new_arr, label])

In [5]:
data


[[array([[ 43,  47,  33, ...,  24,  17,  27],
         [ 42,  45,  43, ...,  31,  10,  30],
         [ 47,  37,  39, ..., 164, 175, 191],
         ...,
         [122, 125, 126, ..., 124,  80, 114],
         [125, 123, 125, ..., 152,  60, 122],
         [126, 127, 124, ...,  60,  97, 108]], dtype=uint8),
  0],
 [array([[ 56,  53,  61, ...,  11,  11,  11],
         [ 93, 107, 112, ...,  18,  20,  21],
         [105, 112, 119, ...,  23,  24,  32],
         ...,
         [ 91,  82,  69, ...,  86,  90,  94],
         [ 83,  88,  53, ...,  78,  80,  80],
         [ 39,  20,   7, ...,  63,  63,  64]], dtype=uint8),
  0],
 [array([[ 79, 113, 139, ..., 157, 154, 154],
         [123, 123,  99, ..., 161, 106, 140],
         [134, 115,  55, ..., 156,  90,  93],
         ...,
         [101,  96, 102, ..., 185, 169, 122],
         [ 99,  97,  96, ..., 177, 181, 122],
         [112, 104, 102, ..., 186, 177, 170]], dtype=uint8),
  0],
 [array([[231, 233, 232, ..., 118, 115, 114],
         [232, 233, 2

In [6]:
len(data)

2000

In [7]:
random.shuffle(data)
data


[[array([[130, 133, 132, ..., 177, 124, 154],
         [ 43,  47,  46, ..., 177, 127, 147],
         [108, 128, 126, ..., 177, 122, 142],
         ...,
         [ 55,  83,  75, ..., 115, 100, 116],
         [ 77,  88,  99, ..., 100,  92,  94],
         [ 72,  77,  83, ...,  94, 121,  95]], dtype=uint8),
  0],
 [array([[101,  58,  87, ...,  45,  39,  32],
         [ 55,  72,  79, ...,  54,  50,  48],
         [ 67, 113,  46, ...,  57,  57,  56],
         ...,
         [130, 134, 133, ..., 140, 143, 137],
         [127, 130, 130, ..., 143, 138, 137],
         [130, 133, 126, ..., 140, 138, 138]], dtype=uint8),
  1],
 [array([[144, 128, 121, ..., 116, 120, 108],
         [142, 129, 116, ..., 121, 118, 121],
         [155, 131, 119, ..., 109, 124, 127],
         ...,
         [ 37,  39,  43, ...,  50,  40,  47],
         [ 43,  46,  45, ...,  40,  35,  38],
         [ 40,  45,  43, ...,  34,  43,  46]], dtype=uint8),
  0],
 [array([[ 83,  29, 158, ..., 123, 128, 133],
         [ 58,  84, 1

In [8]:
X =[]
Y =[]
for features, labels in data:
    X.append(features)
    Y.append(labels)

In [9]:
X=np.array(X)
Y=np.array(Y)

In [10]:
pickle.dump(X, open('X.pkl', 'wb'))
pickle.dump(Y, open('Y.pkl', 'wb'))

In [47]:
## IMAGE CLASSIFICATION

In [11]:
import pickle
X = pickle.load(open('X.pkl', 'rb'))
y = pickle.load(open('y.pkl', 'rb'))
X

array([[[130, 133, 132, ..., 177, 124, 154],
        [ 43,  47,  46, ..., 177, 127, 147],
        [108, 128, 126, ..., 177, 122, 142],
        ...,
        [ 55,  83,  75, ..., 115, 100, 116],
        [ 77,  88,  99, ..., 100,  92,  94],
        [ 72,  77,  83, ...,  94, 121,  95]],

       [[101,  58,  87, ...,  45,  39,  32],
        [ 55,  72,  79, ...,  54,  50,  48],
        [ 67, 113,  46, ...,  57,  57,  56],
        ...,
        [130, 134, 133, ..., 140, 143, 137],
        [127, 130, 130, ..., 143, 138, 137],
        [130, 133, 126, ..., 140, 138, 138]],

       [[144, 128, 121, ..., 116, 120, 108],
        [142, 129, 116, ..., 121, 118, 121],
        [155, 131, 119, ..., 109, 124, 127],
        ...,
        [ 37,  39,  43, ...,  50,  40,  47],
        [ 43,  46,  45, ...,  40,  35,  38],
        [ 40,  45,  43, ...,  34,  43,  46]],

       ...,

       [[177, 136, 175, ...,  42,  42,  41],
        [150, 146, 141, ...,  44,  44,  42],
        [206, 214, 140, ...,  42,  42,  44

In [12]:
Y

array([0, 1, 0, ..., 1, 0, 1])

In [13]:
X = X/255
X

array([[[0.50980392, 0.52156863, 0.51764706, ..., 0.69411765,
         0.48627451, 0.60392157],
        [0.16862745, 0.18431373, 0.18039216, ..., 0.69411765,
         0.49803922, 0.57647059],
        [0.42352941, 0.50196078, 0.49411765, ..., 0.69411765,
         0.47843137, 0.55686275],
        ...,
        [0.21568627, 0.3254902 , 0.29411765, ..., 0.45098039,
         0.39215686, 0.45490196],
        [0.30196078, 0.34509804, 0.38823529, ..., 0.39215686,
         0.36078431, 0.36862745],
        [0.28235294, 0.30196078, 0.3254902 , ..., 0.36862745,
         0.4745098 , 0.37254902]],

       [[0.39607843, 0.22745098, 0.34117647, ..., 0.17647059,
         0.15294118, 0.1254902 ],
        [0.21568627, 0.28235294, 0.30980392, ..., 0.21176471,
         0.19607843, 0.18823529],
        [0.2627451 , 0.44313725, 0.18039216, ..., 0.22352941,
         0.22352941, 0.21960784],
        ...,
        [0.50980392, 0.5254902 , 0.52156863, ..., 0.54901961,
         0.56078431, 0.5372549 ],
        [0.4

In [ ]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten
model = Sequential()

model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Flatten())

model.add(Dense(128, input_shape = X.shape[1:], activation = 'relu'))

model.add(Dense(2, activation = 'softmax'))

In [ ]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
model.fit(X, y, epochs=5, validation_split=0.1)

In [ ]:
X.shape

In [3]:
import time

time.time()

1699726169.8185973

In [4]:
type(1699726169.8185973)

float

In [6]:
##FINAL PREDICTION

In [ ]:
import cv2
import keras

In [ ]:
import numpy as np
CATEGORIES = ['Cat', 'Dog']


def image(path):
    img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
    new_arr = cv2.resize(img, (60, 60))
    new_arr = np.array(new_arr)
    new_arr = new_arr.reshape(-1, 60, 60, 1)
    return new_arr

model = keras.models.load_model('3x3x64-catvsdog.model')
prediction = model.predict([image('test_of_model/puppy.jpg')])
print(CATEGORIES[prediction.argmax()])